version: '1.0'
stages:
- prepare
- apply
steps:
  main_clone:
   title: Cloning repository
   type: git-clone
   repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
   revision: "${{CF_BRANCH}}"
   stage: prepare
  plan:
   image: alpine/terragrunt
   title: Outputting Terraform plan
   stage: apply
   commands:
    - terragrunt plan
  approve apply:
    type: pending-approval
    title: confirm apply
    stage: apply
    description: apply confirm
    timeout:
      duration: 2
      finalState: approved
      timeUnit: minutes
    when:
      branch:
        only: [ main ]
  apply:
   image: alpine/terragrunt
   title: Applying Terraform
   stage: apply
   commands:
    - terragrunt apply -auto-approve
   when:
    branch:
     only:
      - main
