version: '1.0'
stages:
- prepare
- apply
steps:
  main_clone:
   title: Cloning repository
   type: git-clone
   repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
   revision: "${{CF_BRANCH}}"
   stage: prepare
  init:
   image: alpine/terragrunt
   title: Initializing Terraform
   stage: apply
   commands:
    - terragrunt init
  plan:
    image: alpine/terragrunt
    title: Outputting Terraform plan
    stage: apply
    commands: 
     - terragrunt init && terragrunt run-all plan
  approve apply:
    type: pending-approval
    title: confirm apply
    stage: apply
    description: apply confirm
    timeout:
      duration: 2
      finalState: approved
      timeUnit: minutes
    when:
      branch:
        only: [ main ]
  apply:
   image: alpine/terragrunt
   title: Applying Terraform
   stage: apply
   commands:
    - terragrunt run-all apply -auto-approve
   when:
    branch:
     only:
      - main
